locale = "zh-tw"
label = "繁體中文"
weight = 9
title = "Leia's Notes"

[params]
  displayName = "繁體中文"
  isoCode = "zh-tw"
  rtl = false
  dateFormat = "2006-01-02"
  logo = "logo_moon.png"
  description = "Scribbles on software, thoughts, and everyday life."

[params.author]
  name = "Leia"
  email = "daodao0988@gmail.com"
  image = "logo_moon.png"
  headline = "SWE | Build · Breathe · Live"

