locale = "en"
label = "English"
weight = 1
title = "Leia's Notes"

[params]
displayName = "English"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
logo = "logo_moon.png"
description = "Scribbles on software, thoughts, and everyday life."

[params.author]
name = "Leia"
email = "daodao0988@gmail.com"
image = "logo_moon.png"
headline = "SWE | Build · Breathe · Live"
