[[main]]
  name = "Home"
  pageRef = "/"
  weight = 10

[[main]]
  name = "Posts"
  weight = 20

[[main]]
  name = "All"
  pageRef = "/posts"
  parent = "Posts"
  weight = 21

[[main]]
  name = "Topics"
  pageRef = "/categories"
  parent = "Posts"
  weight = 22

[[main]]
  name = "Tags"
  pageRef = "/tags"
  parent = "Posts"
  weight = 23

[[main]]
  name = "About"
  pageRef = "/about"
  weight = 30

[[footer]]
  name = "Tags"
  pageRef = "tags"
  weight = 10
