colorScheme = "noir"
defaultAppearance = "dark"
autoSwitchAppearance = true
enableA11y = false
enableSearch = true
enableCodeCopy = true
enableStructuredBreadcrumbs = true
replyByEmail = false
mainSections = [ "posts" ]
disableImageOptimization = false
disableImageOptimizationMD = false
disableTextInHeader = false
defaultBackgroundImage = "/img/background.svg"
defaultFeaturedImage = "/img/featured.svg"
defaultSocialImage = "logo_moon.png"
hotlinkFeatureImage = false
highlightCurrentMenuArea = true
smartTOC = true
smartTOCHideUnfocusedChildren = false
fingerprintAlgorithm = "sha512"
fathomAnalytics = { }
umamiAnalytics = { }
selineAnalytics = { }
verification = { }
rssnext = { }
advertisement = { }

[header]
layout = "fixed"

[footer]
showMenu = true
showCopyright = true
showThemeAttribution = false
showAppearanceSwitcher = true
showScrollToTop = true

[homepage]
layout = "custom"
showRecent = false
showRecentItems = 12
showMoreLink = true
showMoreLinkDest = "posts"
cardView = true
cardViewScreenWidth = false
layoutBackgroundBlur = true
disableHeroImageFilter = false

[article]
showDate = false
showViews = false
showLikes = false
showDateOnlyInArticle = false
showDateUpdated = false
showAuthor = true
showHero = true
heroStyle = "background"
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = true
showBreadcrumbs = true
showDraftLabel = true
showEdit = false
editURL = "https://github.com/nunocoracao/blowfish/tree/main/exampleSite/content"
editAppendPath = true
seriesOpened = false
showHeadingAnchors = true
showPagination = true
invertPagination = false
showReadingTime = true
showTableOfContents = true
showRelatedContent = true
relatedContentLimit = 9
showTaxonomies = true
showAuthorsBadges = true
showWordCount = false
sharingLinks = [
  "linkedin",
  "twitter",
  "bluesky",
  "reddit",
  "whatsapp",
  "telegram",
  "pinterest",
  "facebook",
  "email",
  "line"
]
showZenMode = true

[list]
showHero = true
heroStyle = "background"
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = false
showBreadcrumbs = false
showSummary = false
showViews = false
showLikes = false
showTableOfContents = true
showCards = true
orderByWeight = true
groupByYear = false
cardView = true
cardViewScreenWidth = false
constrainItemsWidth = false

[sitemap]
excludedKinds = [ ]

[taxonomy]
showTermCount = true
showHero = true
heroStyle = "background"
showBreadcrumbs = false
showViews = false
showLikes = false
showTableOfContents = true
cardView = false

[term]
showHero = true
heroStyle = "background"
showBreadcrumbs = false
showViews = false
showLikes = false
showTableOfContents = true
groupByYear = false
cardView = true
cardViewScreenWidth = false

[firebase]
apiKey = "AIzaSyB5tqlqDky77Vb4Tc4apiHV4hRZI18KGiY"
authDomain = "blowfish-21fff.firebaseapp.com"
projectId = "blowfish-21fff"
storageBucket = "blowfish-21fff.appspot.com"
messagingSenderId = "60108104191"
appId = "1:60108104191:web:039842ebe1370698b487ca"
measurementId = "G-PEDMYR1V0K"

[buymeacoffee]
identifier = "Leia"
globalWidget = true
globalWidgetMessage = ""
globalWidgetColor = "#FFDD00"
globalWidgetPosition = "right"
